{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "NIXPACKS",
    "buildCommand": "cd backend && npm install"
  },
  "deploy": {
    "startCommand": "cd backend && npm start",
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 10
  },
  "environments": {
    "production": {
      "variables": {
        "NODE_ENV": "production",
        "PORT": "${{RAILWAY_PORT}}",
        "MONGODB_URI": "${{MONGODB_URI}}",
        "JWT_SECRET": "${{JWT_SECRET}}",
        "CLIENT_URL": "https://kmt-event-management.netlify.app"
      }
    }
  }
}